name: Docs

on:
  push:
    branches: [ master ]
    ## For Testing
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Build documentation
        run: |
          chmod +x gradlew
          ./gradlew dokkaHtml

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ai/build/dokka/html